/**
 * GRIEVANCES (GS) — what one seat holds against another for what it did.
 *
 * CIV6: the score is "organized as a coordinate system, with the 'neutral'
 * point, 0, and Civilizations A and B standing on the two sides of the neutral
 * point", so the storage is ONE signed balance per unordered pair, keyed like
 * every other pair clock. A positive balance for the lower seat means the
 * lower seat is the VICTIM and the higher seat is the transgressor.
 *
 * Everything a rule asks of the ledger goes through `grievanceWith` (signed,
 * from one seat's side) or `grievancesAgainst` (what the whole world holds
 * against one seat), so no caller ever touches the key.
 */
import type { GameState } from './types';
import { warIsGolden, citiesOf, civsAtWar, friendTurnsWith, seatOf, seatsAllied, warClockKey } from './seats';
import { worldEraIndex } from './eras';
import { congressGrievanceMult } from './congress';
import { getModifiers } from './effects';
import { GOLDEN_WAR_GRIEVANCE_PCT,
  GRIEVANCE_ALLY_SHARE,
  GRIEVANCE_CITY_RAZED,
  GRIEVANCE_CITY_TAKEN,
  GRIEVANCE_CS_CONQUERED,
  GRIEVANCE_CS_RAZED,
  GRIEVANCE_DECAY_BASE,
  GRIEVANCE_DECAY_FLOOR,
  GRIEVANCE_DENOUNCE,
  GRIEVANCE_FAVOR_FLOOR,
  GRIEVANCE_FAVOR_MAX,
  GRIEVANCE_FAVOR_STEP,
  GRIEVANCE_FRIEND_SHARE,
  GRIEVANCE_HELD_CAPITAL_PER_TURN,
  GRIEVANCE_LAST_CITY,
  GRIEVANCE_OCCUPIED_CAPITAL_DECAY,
  GRIEVANCE_OCCUPIED_DECAY,
  GRIEVANCE_WAR_FORMAL,
  GRIEVANCE_WAR_ON_CS_FRIEND,
  GRIEVANCE_WAR_ON_FRIEND,
  GRIEVANCE_WAR_ON_SUZERAIN,
  GRIEVANCE_WAR_SURPRISE,
} from '../data/seats';

/** what `a` holds against `b`, signed: positive = b transgressed against a. */
export function grievanceWith(state: GameState, a: number, b: number): number {
  if (a === b) return 0;
  const v = state.grievances?.[warClockKey(a, b)] ?? 0;
  return (a < b ? v : -v) || 0;  // never a signed zero: the digest compares it
}

/** tip the pair's balance by `n` toward `victim`. Negative `n` pays it back. */
export function addGrievance(state: GameState, victim: number, transgressor: number, n: number): void {
  if (victim === transgressor || n === 0) return;
  if (!seatOf(state, victim) || !seatOf(state, transgressor)) return;
  // PUBLIC RELATIONS scales what an act GENERATES. A decay step pays the pair
  // back and is not generated by anyone, so only a positive write is scaled.
  const amt = n > 0
    ? Math.floor((n * congressGrievanceMult(state, victim, transgressor)) / 100)
    : n;
  if (amt === 0) return;
  if (!state.grievances) state.grievances = {};
  const key = warClockKey(victim, transgressor);
  const signed = victim < transgressor ? amt : -amt;
  const next = (state.grievances[key] ?? 0) + signed;
  if (next === 0) delete state.grievances[key];
  else state.grievances[key] = next;
}

/**
 * The transgressor's whole bill: what every OTHER major currently holds
 * against it. A pair the transgressor is winning contributes nothing — the
 * balance is already on its side of the neutral point.
 */
export function grievancesAgainst(state: GameState, seat: number): number {
  let n = 0;
  for (const s of state.seats) {
    if (s.seat === seat) continue;
    n += Math.max(0, grievanceWith(state, s.seat, seat));
  }
  return n;
}

/**
 * CIV6 (Diplomatic Favor, "Losing Favor"): "200 Grievance = -1 Diplomatic
 * Favor. Every 50 Grievance = -1 Diplomatic Favor", "it could reach as much
 * as -10/turn".
 */
export function grievanceFavorPenalty(state: GameState, seat: number): number {
  const g = grievancesAgainst(state, seat);
  if (g < GRIEVANCE_FAVOR_FLOOR) return 0;
  const steps = 1 + Math.floor((g - GRIEVANCE_FAVOR_FLOOR) / GRIEVANCE_FAVOR_STEP);
  return Math.min(GRIEVANCE_FAVOR_MAX, steps);
}

/** the cities `holder` took from `founder` — 0, or the worse capital case. */
function occupationOf(state: GameState, holder: number, founder: number): number {
  let held = 0;
  for (const c of citiesOf(state, holder)) {
    if ((c.origCapitalSeat ?? -1) === founder) return GRIEVANCE_OCCUPIED_CAPITAL_DECAY;
    if ((c.founderSeat ?? -1) === founder) held = GRIEVANCE_OCCUPIED_DECAY;
  }
  return held;
}

/**
 * CIV6: "as long as the two civs are not at war with each other, those
 * Grievances will eventually be gone", at "10 - x per turn, where x is each
 * era after the Ancient Era" — slower by the occupation modifier for the
 * party whose cities are held, faster for the party holding them.
 *
 * Runs on the LOWER seat of each pair so one turn decays each pair once.
 */
export function decayGrievances(state: GameState, seat: number): void {
  const base = Math.max(GRIEVANCE_DECAY_FLOOR, GRIEVANCE_DECAY_BASE - Math.max(0, worldEraIndex(state)));
  for (const other of state.seats) {
    if (other.seat <= seat) continue;
    if (civsAtWar(state, seat, other.seat)) continue;
    const bal = grievanceWith(state, seat, other.seat);
    if (bal === 0) continue;
    const victim = bal > 0 ? seat : other.seat;
    const transgressor = bal > 0 ? other.seat : seat;
    // CIV6 (Cyber Warfare): "Grievances against you do not decay" — the
    // TRANSGRESSOR's card holds what it is owed for.
    if (getModifiers(state, transgressor).grievanceNoDecay) continue;
    const rate = base - occupationOf(state, transgressor, victim) + occupationOf(state, victim, transgressor);
    const step = Math.min(Math.abs(bal), Math.max(0, rate));
    if (step > 0) addGrievance(state, victim, transgressor, -step);
  }
}

/**
 * A DECLARATION. CIV6 pays the target "Surprise War declared: 150" or
 * "Formal War declared: 100", and every friend or ally of the target
 * "War declared on a Friend or Ally: 75".
 */
export function grievanceWarDeclared(state: GameState, declarer: number, target: number, formal: boolean, golden = false): void {
  // CIV6 (Golden Age War): "only 25% warmonger penalty for
  // declaration/captures" — a formal-war declaration at a quarter.
  const base = formal ? GRIEVANCE_WAR_FORMAL : GRIEVANCE_WAR_SURPRISE;
  spreadGrievance(state, target, declarer,
    golden ? Math.round((base * GOLDEN_WAR_GRIEVANCE_PCT) / 100) : base);
  for (const s of state.seats) {
    if (s.seat === declarer || s.seat === target) continue;
    if (seatsAllied(state, s.seat, target) || friendTurnsWith(state, s.seat, target) > 0) {
      addGrievance(state, s.seat, declarer, GRIEVANCE_WAR_ON_FRIEND);
    }
  }
}

/**
 * CIV6: "War declared on a city-state a civ is the Suzerain over: 100", and
 * "War declared on a city-state friend or ally: 50 (to every civ that has at
 * least 1 Envoy in that city-state, but is not its Suzerain)".
 */
export function grievanceCityStateWar(
  state: GameState,
  declarer: number,
  suzerain: number,
  envoyHolders: readonly number[],
): void {
  if (suzerain >= 0 && suzerain !== declarer) {
    addGrievance(state, suzerain, declarer, GRIEVANCE_WAR_ON_SUZERAIN);
  }
  for (const s of envoyHolders) {
    if (s === declarer || s === suzerain) continue;
    addGrievance(state, s, declarer, GRIEVANCE_WAR_ON_CS_FRIEND);
  }
}

/** "City Occupied (capturing a city during war)", and its 3x razed row. */
export function grievanceCityTaken(state: GameState, taker: number, loser: number, razed: boolean): void {
  const base = razed ? GRIEVANCE_CITY_RAZED : GRIEVANCE_CITY_TAKEN;
  // CIV6 (Golden Age War): captures at a quarter too; the razing rows are
  // their own published figures and stay whole.
  const golden = !razed && warIsGolden(state, taker, loser);
  spreadGrievance(state, loser, taker,
    golden ? Math.round((base * GOLDEN_WAR_GRIEVANCE_PCT) / 100) : base);
}

/**
 * CIV6: "Captured the final city of a civilization: 150 (all remaining civs
 * gain Grievances against you)", and the two city-state rows that read the
 * same way — "City-state conquered: 50 (all civs gain Grievances against
 * you)", "City-state razed: 100".
 */
export function grievanceAgainstTheWorld(state: GameState, transgressor: number, n: number): void {
  for (const s of state.seats) {
    if (s.seat === transgressor) continue;
    addGrievance(state, s.seat, transgressor, n);
  }
}

export function grievanceLastCity(state: GameState, taker: number): void {
  grievanceAgainstTheWorld(state, taker, GRIEVANCE_LAST_CITY);
}

export function grievanceCityStateTaken(state: GameState, taker: number, razed: boolean): void {
  grievanceAgainstTheWorld(state, taker, razed ? GRIEVANCE_CS_RAZED : GRIEVANCE_CS_CONQUERED);
}

/** "Denounced: 25". */
export function grievanceDenounce(state: GameState, denouncer: number, target: number): void {
  spreadGrievance(state, target, denouncer, GRIEVANCE_DENOUNCE);
}

/**
 * CIV6: "Controlling the civ's original Capital: 3 per turn while not at war".
 * The row below it in the same table — 1 per turn for any other city the civ
 * founded — is marked "(not working anymore)" and has no twin here.
 */
export function grievanceHeldCapitals(state: GameState, seat: number): void {
  for (const c of citiesOf(state, seat)) {
    const orig = c.origCapitalSeat ?? -1;
    if (orig < 0 || orig === seat) continue;
    if (!seatOf(state, orig) || civsAtWar(state, seat, orig)) continue;
    addGrievance(state, orig, seat, GRIEVANCE_HELD_CAPITAL_PER_TURN);
  }
}

/**
 * CIV6: "If Civilization A commits acts that generate Grievances from
 * Civilization B, allies of B will gain 50% of B's Grievances against A, and
 * declared friends of B will gain 25%." The share is of the SAME act, so it
 * is paid at the act, not swept later.
 */
function spreadGrievance(state: GameState, victim: number, transgressor: number, n: number): void {
  addGrievance(state, victim, transgressor, n);
  for (const s of state.seats) {
    if (s.seat === victim || s.seat === transgressor) continue;
    const share = seatsAllied(state, s.seat, victim)
      ? GRIEVANCE_ALLY_SHARE
      : friendTurnsWith(state, s.seat, victim) > 0 ? GRIEVANCE_FRIEND_SHARE : 0;
    if (share > 0) addGrievance(state, s.seat, transgressor, Math.floor((n * share) / 100));
  }
}
