from __future__ import annotations

from .simbase import *  # noqa: F401,F403 — torch, constants, helpers: the shared floor


class SimGriev:
    """GRIEVANCES — the `cpu/core/grievance.ts` twin.

    `civ_grievance[b, i, j]` is what seat i holds against seat j, ANTISYMMETRIC
    by construction: every write pays one cell and its mirror, so the pair
    carries exactly one signed balance, which is what the TS map keyed on the
    unordered pair carries. Only MAJOR rows are ever written.
    """

    # ------------------------------------------------------------------ store
    def _add_grievance(self, victim: int, transgressor: int, n, m=None, *, generated=True) -> None:
        """tip the pair's balance by `n` toward `victim` where `m` holds.
        `generated` is False for a PAYBACK, which no seat commits and PUBLIC
        RELATIONS therefore never scales — the decay tips whichever side of the
        pair is losing, so its sign alone cannot say which is which."""
        if victim == transgressor:
            return
        amt = n if torch.is_tensor(n) else torch.full((self.B,), int(n), dtype=torch.long, device=self.device)
        amt = amt.long()
        # PUBLIC RELATIONS scales what an act GENERATES. A decay step pays the
        # pair back and is not generated by anyone, so only a positive write
        # is scaled.
        if generated:
            _mult = self._congress_grievance_mult(victim, transgressor)
            amt = torch.where(amt > 0, torch.div(amt * _mult, 100, rounding_mode="floor"), amt)
        if m is not None:
            amt = torch.where(m, amt, torch.zeros_like(amt))
        if not bool((amt != 0).any()):
            return
        self.civ_grievance[:, victim, transgressor] += amt
        self.civ_grievance[:, transgressor, victim] -= amt

    def _grievance_with(self, a: int, b: int) -> torch.Tensor:
        """[B] signed, from `a`'s side: positive = b transgressed against a."""
        return self.civ_grievance[:, a, b]

    def _grievances_against(self, row: int) -> torch.Tensor:
        """[B] what every OTHER major holds against `row`. A pair `row` is
        winning contributes nothing — the balance is already on its side."""
        return self.civ_grievance[:, : self.n_majors, row].clamp(min=0).sum(dim=1)

    def _grievance_favor_penalty(self, row: int) -> torch.Tensor:
        g = self._grievances_against(row)
        steps = 1 + (g - self._griev_favor_floor).div(self._griev_favor_step, rounding_mode="floor")
        return torch.where(g < self._griev_favor_floor, torch.zeros_like(steps),
                           steps.clamp(max=self._griev_favor_max))

    # ------------------------------------------------------------------ decay
    def _occupation_of(self, holder: int, founder: int) -> torch.Tensor:
        """[B] the decay modifier `holder` earns for sitting in `founder`'s
        cities: the capital rate if it holds the original capital, the flat
        one for any other city it founded, else nothing."""
        alive = self.city_alive[:, holder]
        cap = (alive & (self.city_orig_cap[:, holder] == founder)).any(dim=1)
        any_city = (alive & (self.city_founder[:, holder] == founder)).any(dim=1)
        return torch.where(cap, torch.full_like(cap, self._griev_occ_cap_decay, dtype=torch.long),
                           any_city.long() * self._griev_occ_decay)

    def _grievance_decay(self, row: int) -> None:
        """CIV6: "10 - x per turn, where x is each era after the Ancient Era",
        never while that pair is at war. Runs on the LOWER seat of each pair so
        one turn decays each pair once."""
        base = (self._griev_decay_base - self._world_era().clamp(min=0)).clamp(min=self._griev_decay_floor)
        for other in range(row + 1, self.n_majors):
            bal = self._grievance_with(row, other)
            live = (bal != 0) & ~self.war[:, row, other]
            if not bool(live.any()):
                continue
            # the victim's side of the pair, per game
            v_is_row = bal > 0
            rate = base.clone()
            for v, t in ((row, other), (other, row)):
                side = v_is_row if v == row else ~v_is_row
                rate = torch.where(side, base - self._occupation_of(t, v) + self._occupation_of(v, t), rate)
            step = torch.minimum(bal.abs(), rate.clamp(min=0)) * live.long()
            self._add_grievance(row, other, torch.where(v_is_row, -step, step), generated=False)

    def _grievance_held_capitals(self, row: int) -> None:
        """CIV6: "Controlling the civ's original Capital: 3 per turn while not
        at war". The table's 1/turn row for any other founded city is marked
        "(not working anymore)" and has no twin here."""
        alive = self.city_alive[:, row]
        for other in range(self.n_majors):
            if other == row:
                continue
            hold = (alive & (self.city_orig_cap[:, row] == other)).any(dim=1) & ~self.war[:, row, other]
            self._add_grievance(other, row, self._griev_held_capital, hold)

    # ------------------------------------------------------------------ events
    def _spread_grievance(self, victim: int, transgressor: int, n: int, m) -> None:
        """CIV6: "allies of B will gain 50% of B's Grievances against A, and
        declared friends of B will gain 25%"."""
        self._add_grievance(victim, transgressor, n, m)
        for s in range(self.n_majors):
            if s in (victim, transgressor):
                continue
            allied = self.seat_ally_turns[:, s, victim] > 0
            friend = self.seat_friend_turns[:, s, victim] > 0
            share = torch.where(allied, torch.full_like(allied, self._griev_ally_share, dtype=torch.long),
                                friend.long() * self._griev_friend_share)
            self._add_grievance(s, transgressor, (share * n).div(100, rounding_mode="floor"), m)

    def _grievance_war_declared(self, declarer: int, target: int, m, formal) -> None:
        """"Surprise War declared: 150" / "Formal War declared: 100", and
        "War declared on a Friend or Ally: 75" to each of the target's."""
        surprise = m & ~formal
        self._spread_grievance(target, declarer, self._griev_war_surprise, surprise)
        self._spread_grievance(target, declarer, self._griev_war_formal, m & formal)
        for s in range(self.n_majors):
            if s in (declarer, target):
                continue
            near = (self.seat_ally_turns[:, s, target] > 0) | (self.seat_friend_turns[:, s, target] > 0)
            self._add_grievance(s, declarer, self._griev_war_on_friend, m & near)

    def _grievance_city_taken(self, b: int, taker: int, loser: int, razed: bool) -> None:
        one = torch.zeros(self.B, dtype=torch.bool, device=self.device)
        one[b] = True
        self._spread_grievance(loser, taker, self._griev_city_razed if razed else self._griev_city_taken, one)

    def _grievance_world(self, transgressor: int, n: int, m) -> None:
        """the three rows every civ reads: the last city of a civilization, a
        city-state conquered, a city-state razed."""
        for s in range(self.n_majors):
            if s == transgressor:
                continue
            self._add_grievance(s, transgressor, n, m)

    def _grievance_last_city(self, b: int, taker: int) -> None:
        one = torch.zeros(self.B, dtype=torch.bool, device=self.device)
        one[b] = True
        self._grievance_world(taker, self._griev_last_city, one)

    def _grievance_cs_taken(self, taker: int, razed, m) -> None:
        self._grievance_world(taker, self._griev_cs_razed, m & razed)
        self._grievance_world(taker, self._griev_cs_conquered, m & ~razed)

    def _grievance_denounce(self, denouncer: int, target: int, m) -> None:
        self._spread_grievance(target, denouncer, self._griev_denounce, m)

    def _grievance_cs_war(self, declarer: int, cs: int, m) -> None:
        """"War declared on a city-state a civ is the Suzerain over: 100", and
        "War declared on a city-state friend or ally: 50 (to every civ that has
        at least 1 Envoy in that city-state, but is not its Suzerain)"."""
        for s in range(self.n_majors):
            if s == declarer:
                continue
            suz = self._suzerain_mask(s)[:, cs]
            self._add_grievance(s, declarer, self._griev_war_on_suzerain, m & suz)
            envoy = self.seat_citystate_envoys[:, s, cs] > 0
            self._add_grievance(s, declarer, self._griev_war_on_cs_friend, m & envoy & ~suz)
